// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ./paymentrequest.proto
package org.bitcoin.protocols.payments;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import okio.ByteString;

import static com.squareup.wire.Message.Datatype.*;
import static com.squareup.wire.Message.Label.REQUIRED;

public final class PaymentRequest extends Message {
  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_PAYMENT_DETAILS_VERSION = 1;
  public static final String DEFAULT_PKI_TYPE = "none";
  public static final ByteString DEFAULT_PKI_DATA = ByteString.EMPTY;
  public static final ByteString DEFAULT_SERIALIZED_PAYMENT_DETAILS = ByteString.EMPTY;
  public static final ByteString DEFAULT_SIGNATURE = ByteString.EMPTY;

  @ProtoField(tag = 1, type = UINT32)
  public final Integer payment_details_version;

  @ProtoField(tag = 2, type = STRING)
  public final String pki_type;

  /**
   * none / x509+sha256 / x509+sha1
   */
  @ProtoField(tag = 3, type = BYTES)
  public final ByteString pki_data;

  /**
   * depends on pki_type
   */
  @ProtoField(tag = 4, type = BYTES, label = REQUIRED)
  public final ByteString serialized_payment_details;

  /**
   * PaymentDetails
   */
  @ProtoField(tag = 5, type = BYTES)
  public final ByteString signature;

  public PaymentRequest(Integer payment_details_version, String pki_type, ByteString pki_data, ByteString serialized_payment_details, ByteString signature) {
    this.payment_details_version = payment_details_version;
    this.pki_type = pki_type;
    this.pki_data = pki_data;
    this.serialized_payment_details = serialized_payment_details;
    this.signature = signature;
  }

  private PaymentRequest(Builder builder) {
    this(builder.payment_details_version, builder.pki_type, builder.pki_data, builder.serialized_payment_details, builder.signature);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PaymentRequest)) return false;
    PaymentRequest o = (PaymentRequest) other;
    return equals(payment_details_version, o.payment_details_version)
        && equals(pki_type, o.pki_type)
        && equals(pki_data, o.pki_data)
        && equals(serialized_payment_details, o.serialized_payment_details)
        && equals(signature, o.signature);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = payment_details_version != null ? payment_details_version.hashCode() : 0;
      result = result * 37 + (pki_type != null ? pki_type.hashCode() : 0);
      result = result * 37 + (pki_data != null ? pki_data.hashCode() : 0);
      result = result * 37 + (serialized_payment_details != null ? serialized_payment_details.hashCode() : 0);
      result = result * 37 + (signature != null ? signature.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PaymentRequest> {

    public Integer payment_details_version;
    public String pki_type;
    public ByteString pki_data;
    public ByteString serialized_payment_details;
    public ByteString signature;

    public Builder() {
    }

    public Builder(PaymentRequest message) {
      super(message);
      if (message == null) return;
      this.payment_details_version = message.payment_details_version;
      this.pki_type = message.pki_type;
      this.pki_data = message.pki_data;
      this.serialized_payment_details = message.serialized_payment_details;
      this.signature = message.signature;
    }

    public Builder payment_details_version(Integer payment_details_version) {
      this.payment_details_version = payment_details_version;
      return this;
    }

    public Builder pki_type(String pki_type) {
      this.pki_type = pki_type;
      return this;
    }

    /**
     * none / x509+sha256 / x509+sha1
     */
    public Builder pki_data(ByteString pki_data) {
      this.pki_data = pki_data;
      return this;
    }

    /**
     * depends on pki_type
     */
    public Builder serialized_payment_details(ByteString serialized_payment_details) {
      this.serialized_payment_details = serialized_payment_details;
      return this;
    }

    /**
     * PaymentDetails
     */
    public Builder signature(ByteString signature) {
      this.signature = signature;
      return this;
    }

    @Override
    public PaymentRequest build() {
      checkRequiredFields();
      return new PaymentRequest(this);
    }
  }
}
