plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.android)
}

dependencies {
    implementation project(includePrefix + ':libs:nordpol')
    implementation libs.androidx.core
    implementation libs.guava
}

android {
    namespace 'com.btchip'
    compileSdk = libs.versions.android.compileSdk.get().toInteger()

    buildFeatures {
        aidl true
    }

    defaultConfig {
        minSdk = libs.versions.android.minSdk.get().toInteger()
        targetSdk = libs.versions.android.targetSdk.get().toInteger()
    }

    lintOptions {
        xmlReport false
        quiet false
        showAll true
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }

    kotlinOptions {
        jvmTarget = "21"
    }
}
