/**
* Auth API
* Auth API<br> <a href='/changelog'>Changelog</a>
*
* The version of the OpenAPI document: v0.0.50
*
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.mycelium.bequant.remote.client.models



import android.os.Parcelable
import com.fasterxml.jackson.annotation.JsonIgnore
import com.fasterxml.jackson.annotation.JsonInclude
import com.fasterxml.jackson.annotation.JsonProperty
import kotlinx.android.parcel.Parcelize

/**
 *
 * @param email
 * @param otpBackupPassword
 * @param otpCode
 * @param password
 */
@Parcelize
data class AccountAuthRequest (
    @JsonProperty("email")
    val email: String,
    @JsonProperty("password")
    val password: String,
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonProperty("otp_backup_password")
    val otpBackupPassword: String? = null,
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonProperty("otp_code")
    val otpCode: String? = null
) : Parcelable

