/**
* Auth API
* Auth API<br> <a href='/changelog'>Changelog</a>
*
* The version of the OpenAPI document: v0.0.50
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.mycelium.bequant.remote.client.models



import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 * @param comment 
 * @param expireDurationSeconds 
 */
@JsonClass(generateAdapter = true)
data class ApiKeyRequest (
    @Json(name = "comment")
    val comment: kotlin.String? = null,
    @Json(name = "expire_duration_seconds")
    val expireDurationSeconds: kotlin.Long? = null
)

