/**
* Auth API
* Auth API<br> <a href='/changelog'>Changelog</a>
*
* The version of the OpenAPI document: v0.0.50
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.mycelium.bequant.remote.client.models



import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 * @param address1 Required address string
 * @param address2 Optional address string
 * @param birthday YYYY-MM-DD format
 * @param city User's city
 * @param country ISO 3166 country format
 * @param firstName User's first name
 * @param lastName User's last name
 * @param nationality User's country of origin
 * @param zip User's ZIP code
 */
data class KycCreateRequest (
    @JsonProperty("address_1")
    val address1: kotlin.String? = null,
    @JsonProperty("address_2")
    val address2: kotlin.String? = null,
    @JsonProperty("birthday")
    val birthday: kotlin.String? = null,
    @JsonProperty("city")
    val city: kotlin.String? = null,
    @JsonProperty("country")
    val country: kotlin.String? = null,
    @JsonProperty("first_name")
    val firstName: kotlin.String? = null,
    @JsonProperty("last_name")
    val lastName: kotlin.String? = null,
    @JsonProperty("nationality")
    val nationality: kotlin.String? = null,
    @JsonProperty("zip")
    val zip: kotlin.String? = null
)

