/**
* Auth API
* Auth API<br> <a href='/changelog'>Changelog</a>
*
* The version of the OpenAPI document: v0.0.50
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.mycelium.bequant.remote.client.models



import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 * @param address1 Required address string
 * @param address2 Optional address string
 * @param birthday YYYY-MM-DD format
 * @param city User's city
 * @param country ISO 3166 country format
 * @param firstName User's first name
 * @param lastName User's last name
 * @param nationality User's country of origin
 * @param zip User's ZIP code
 */
@JsonClass(generateAdapter = true)
data class KycCreateRequest (
    @Json(name = "address_1")
    val address1: kotlin.String? = null,
    @Json(name = "address_2")
    val address2: kotlin.String? = null,
    @Json(name = "birthday")
    val birthday: kotlin.String? = null,
    @Json(name = "city")
    val city: kotlin.String? = null,
    @Json(name = "country")
    val country: kotlin.String? = null,
    @Json(name = "first_name")
    val firstName: kotlin.String? = null,
    @Json(name = "last_name")
    val lastName: kotlin.String? = null,
    @Json(name = "nationality")
    val nationality: kotlin.String? = null,
    @Json(name = "zip")
    val zip: kotlin.String? = null
)

