/**
* Auth API
* Auth API<br> <a href='/changelog'>Changelog</a>
*
* The version of the OpenAPI document: v0.0.50
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.mycelium.bequant.remote.client.models



import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 * @param message 
 * @param rejectReason 
 * @param requestReason 
 * @param status 
 */
@JsonClass(generateAdapter = true)
data class KycStatusResponse (
    @Json(name = "status")
    val status: kotlin.String,
    @Json(name = "message")
    val message: kotlin.String? = null,
    @Json(name = "reject_reason")
    val rejectReason: kotlin.String? = null,
    @Json(name = "request_reason")
    val requestReason: kotlin.String? = null
)

