/**
* Auth API
* Auth API<br> <a href='/changelog'>Changelog</a>
*
* The version of the OpenAPI document: v0.0.50
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.mycelium.bequant.remote.client.models



import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 * @param filename 
 * @param id 
 */
@JsonClass(generateAdapter = true)
data class KycUserDocFile (
    @Json(name = "filename")
    val filename: kotlin.String,
    @Json(name = "id")
    val id: kotlin.Int
)

