/**
* Auth API
* Auth API<br> <a href='/changelog'>Changelog</a>
*
* The version of the OpenAPI document: v0.0.50
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.mycelium.bequant.remote.client.models



import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 * @param email 
 * @param password 
 */
@JsonClass(generateAdapter = true)
data class RegisterAccountRequest (
    @Json(name = "email")
    val email: kotlin.String,
    @Json(name = "password")
    val password: kotlin.String
)

