/**
* Auth API
* Auth API<br> <a href='/changelog'>Changelog</a>
*
* The version of the OpenAPI document: v0.0.50
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.mycelium.bequant.remote.client.models



import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 * @param text 
 * @param type 
 * @param value 
 */
@JsonClass(generateAdapter = true)
data class SessionIssue (
    @Json(name = "text")
    val text: kotlin.String,
    @Json(name = "type")
    val type: SessionIssue.Type,
    @Json(name = "value")
    val value: kotlin.String
) {

    /**
    * 
    * Values: EmailConfirm,Password,Otp
    */
    enum class Type(override val value: kotlin.String) : com.mycelium.bequant.remote.client.EnumWithValue<kotlin.String> {
    
        @Json(name = "email_confirm")
        EmailConfirm("email_confirm"),
    
        @Json(name = "password")
        Password("password"),
    
        @Json(name = "otp")
        Otp("otp");
    
    }

}

