/**
* Auth API
* Auth API<br> <a href='/changelog'>Changelog</a>
*
* The version of the OpenAPI document: v0.0.50
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.mycelium.bequant.remote.client.models



import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 * @param created 
 * @param name 
 * @param otpId 
 * @param status 
 */
data class TotpResponse (
    @JsonProperty("created")
    val created: kotlin.Long,
    @JsonProperty("name")
    val name: kotlin.String,
    @JsonProperty("otp_id")
    val otpId: kotlin.Long,
    @JsonProperty("status")
    val status: kotlin.String
)

