/**
* Auth API
* Auth API<br> <a href='/changelog'>Changelog</a>
*
* The version of the OpenAPI document: v0.0.50
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.mycelium.bequant.remote.client.models



import android.os.Parcelable
import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import kotlinx.android.parcel.Parcelize

/**
 * 
 * @param backupPassword 
 * @param otpId 
 * @param otpLink 
 */
@JsonClass(generateAdapter = true)
@Parcelize
data class TotpCreateResponse (
    @Json(name = "backup_password")
    val backupPassword: String,
    @Json(name = "otp_id")
    val otpId: Long,
    @Json(name = "otp_link")
    val otpLink: String
) : Parcelable

