/**
* Auth API
* Auth API<br> <a href='/changelog'>Changelog</a>
*
* The version of the OpenAPI document: v0.0.50
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.mycelium.bequant.remote.client.models



import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 * @param created 
 * @param name 
 * @param otpId 
 * @param status 
 */
@JsonClass(generateAdapter = true)
data class TotpResponse (
    @Json(name = "created")
    val created: kotlin.Long,
    @Json(name = "name")
    val name: kotlin.String,
    @Json(name = "otp_id")
    val otpId: kotlin.Long,
    @Json(name = "status")
    val status: kotlin.String
)

