/**
 * API
 * Create API keys in your profile and use public API key as username and secret as password to authorize.
 *
 * The version of the OpenAPI document: 2.19.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.mycelium.bequant.remote.trading.model


import com.squareup.moshi.Json

/**
 *
 * @param address
 * @param paymentId
 * @param publicKey
 */

data class Address(
        @Json(name = "address")
        val address: kotlin.String,
        @Json(name = "paymentId")
        val paymentId: kotlin.String? = null,
        @Json(name = "publicKey")
        val publicKey: kotlin.String? = null
)

