/**
 * API
 * Create API keys in your profile and use public API key as username and secret as password to authorize.
 *
 * The version of the OpenAPI document: 2.19.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.mycelium.bequant.remote.trading.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 * @param timestamp
 * @param open
 * @param close
 * @param min
 * @param max
 * @param volume
 * @param volumeQuote
 */

data class Candle(
        @JsonProperty("timestamp")
        val timestamp: java.util.Date,
        @JsonProperty("open")
        val open: kotlin.String,
        @JsonProperty("close")
        val close: kotlin.String,
        @JsonProperty("min")
        val min: kotlin.String,
        @JsonProperty("max")
        val max: kotlin.String,
        @JsonProperty("volume")
        val volume: kotlin.String,
        @JsonProperty("volumeQuote")
        val volumeQuote: kotlin.String
)

