/**
* API
* Create API keys in your profile and use public API key as username and secret as password to authorize. 
*
* The version of the OpenAPI document: 2.19.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.mycelium.bequant.remote.trading.model

import com.mycelium.bequant.remote.trading.model.ErrorError

import com.squareup.moshi.Json
/**
 * 
 * @param error 
 */

data class Error (
    @Json(name = "error")
    val error: ErrorError? = null
)

