/**
 * API
 * Create API keys in your profile and use public API key as username and secret as password to authorize.
 *
 * The version of the OpenAPI document: 2.19.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.mycelium.bequant.remote.trading.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 * @param id
 * @param quantity
 * @param price
 * @param fee
 * @param timestamp
 */

data class OrderTradesReport(
        @JsonProperty("id")
        val id: kotlin.Long? = null,
        @JsonProperty("quantity")
        val quantity: kotlin.String? = null,
        @JsonProperty("price")
        val price: kotlin.String? = null,
        @JsonProperty("fee")
        val fee: kotlin.String? = null,
        @JsonProperty("timestamp")
        val timestamp: java.util.Date? = null
)

