/**
 * API
 * Create API keys in your profile and use public API key as username and secret as password to authorize.
 *
 * The version of the OpenAPI document: 2.19.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.mycelium.bequant.remote.trading.model

import com.squareup.moshi.Json

/**
 *
 * @param id
 * @param clientOrderId
 * @param symbol
 * @param side
 * @param status
 * @param type
 * @param timeInForce
 * @param quantity
 * @param createdAt
 * @param updatedAt
 * @param price
 * @param avgPrice
 * @param cumQuantity
 * @param postOnly
 * @param stopPrice
 * @param expireTime
 * @param positionId Margin position
 * @param tradesReport
 */

data class Order(
        @Json(name = "id")
        val id: kotlin.Long,
        @Json(name = "clientOrderId")
        val clientOrderId: kotlin.String,
        @Json(name = "symbol")
        val symbol: kotlin.String,
        @Json(name = "side")
        val side: Order.Side,
        @Json(name = "status")
        val status: Order.Status,
        @Json(name = "type")
        val type: Order.Type,
        @Json(name = "timeInForce")
        val timeInForce: Order.TimeInForce,
        @Json(name = "quantity")
        val quantity: kotlin.String,
        @Json(name = "createdAt")
        val createdAt: java.time.OffsetDateTime,
        @Json(name = "updatedAt")
        val updatedAt: java.time.OffsetDateTime,
        @Json(name = "price")
        val price: kotlin.String? = null,
        @Json(name = "avgPrice")
        val avgPrice: kotlin.String? = null,
        @Json(name = "cumQuantity")
        val cumQuantity: kotlin.String? = null,
        @Json(name = "postOnly")
        val postOnly: kotlin.Boolean? = null,
        @Json(name = "stopPrice")
        val stopPrice: kotlin.String? = null,
        @Json(name = "expireTime")
        val expireTime: java.time.OffsetDateTime? = null,
        /* Margin position */
        @Json(name = "positionId")
        val positionId: java.math.BigDecimal? = null,
        @Json(name = "tradesReport")
        val tradesReport: OrderTradesReport? = null
) {

    /**
     *
     * Values: sell,buy
     */

    enum class Side(val value: kotlin.String) {
        @Json(name = "sell")
        sell("sell"),
        @Json(name = "buy")
        buy("buy");
    }

    /**
     *
     * Values: new,suspended,partiallyFilled,filled,canceled,expired
     */

    enum class Status(val value: kotlin.String) {
        @Json(name = "new")
        new("new"),
        @Json(name = "suspended")
        suspended("suspended"),
        @Json(name = "partiallyFilled")
        partiallyFilled("partiallyFilled"),
        @Json(name = "filled")
        filled("filled"),
        @Json(name = "canceled")
        canceled("canceled"),
        @Json(name = "expired")
        expired("expired");
    }

    /**
     *
     * Values: limit,market,stopLimit,stopMarket
     */

    enum class Type(val value: kotlin.String) {
        @Json(name = "limit")
        limit("limit"),
        @Json(name = "market")
        market("market"),
        @Json(name = "stopLimit")
        stopLimit("stopLimit"),
        @Json(name = "stopMarket")
        stopMarket("stopMarket");
    }

    /**
     *
     * Values: gTC,iOC,fOK,day,gTD
     */

    enum class TimeInForce(val value: kotlin.String) {
        @Json(name = "GTC")
        gTC("GTC"),
        @Json(name = "IOC")
        iOC("IOC"),
        @Json(name = "FOK")
        fOK("FOK"),
        @Json(name = "Day")
        day("Day"),
        @Json(name = "GTD")
        gTD("GTD");
    }
}

