/**
 * API
 * Create API keys in your profile and use public API key as username and secret as password to authorize.
 *
 * The version of the OpenAPI document: 2.19.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.mycelium.bequant.remote.trading.model


import com.squareup.moshi.Json

/**
 *
 * @param id
 * @param price
 * @param quantity
 * @param side
 * @param timestamp
 */

data class PublicTrade(
        @Json(name = "id")
        val id: kotlin.Int? = null,
        @Json(name = "price")
        val price: kotlin.String? = null,
        @Json(name = "quantity")
        val quantity: kotlin.String? = null,
        @Json(name = "side")
        val side: PublicTrade.Side? = null,
        @Json(name = "timestamp")
        val timestamp: java.util.Date? = null
) {

    /**
     *
     * Values: sell,buy
     */

    enum class Side(val value: kotlin.String) {
        @Json(name = "sell")
        sell("sell"),
        @Json(name = "buy")
        buy("buy");
    }
}

