/**
* API
* Create API keys in your profile and use public API key as username and secret as password to authorize. 
*
* The version of the OpenAPI document: 2.19.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.mycelium.bequant.remote.trading.model


import com.squareup.moshi.Json
/**
 * 
 * @param id 
 * @param baseCurrency 
 * @param quoteCurrency 
 * @param quantityIncrement 
 * @param tickSize A tick size is the minimum price movement of a trading instrument.
 * @param takeLiquidityRate 
 * @param provideLiquidityRate 
 * @param feeCurrency 
 */

data class Symbol (
    @Json(name = "id")
    val id: kotlin.String,
    @Json(name = "baseCurrency")
    val baseCurrency: kotlin.String,
    @Json(name = "quoteCurrency")
    val quoteCurrency: kotlin.String,
    @Json(name = "quantityIncrement")
    val quantityIncrement: kotlin.String,
    /* A tick size is the minimum price movement of a trading instrument. */
    @Json(name = "tickSize")
    val tickSize: kotlin.String,
    @Json(name = "takeLiquidityRate")
    val takeLiquidityRate: kotlin.String? = null,
    @Json(name = "provideLiquidityRate")
    val provideLiquidityRate: kotlin.String? = null,
    @Json(name = "feeCurrency")
    val feeCurrency: kotlin.String? = null
)

