/**
 * API
 * Create API keys in your profile and use public API key as username and secret as password to authorize.
 *
 * The version of the OpenAPI document: 2.19.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.mycelium.bequant.remote.trading.model


import com.squareup.moshi.Json

/**
 *
 * @param id
 * @param index
 * @param currency
 * @param amount
 * @param status
 * @param type
 * @param fee
 * @param address
 * @param paymentId
 * @param hash
 * @param subType
 * @param offchainId
 * @param confirmations
 * @param createdAt
 * @param updatedAt
 * @param errorCode
 */

data class Transaction(
        @Json(name = "id")
        val id: kotlin.String,
        @Json(name = "index")
        val index: kotlin.String,
        @Json(name = "currency")
        val currency: kotlin.String,
        @Json(name = "amount")
        val amount: kotlin.String,
        @Json(name = "status")
        val status: Transaction.Status,
        @Json(name = "type")
        val type: Transaction.Type,
        @Json(name = "fee")
        val fee: kotlin.String? = null,
        @Json(name = "address")
        val address: kotlin.String? = null,
        @Json(name = "paymentId")
        val paymentId: kotlin.String? = null,
        @Json(name = "hash")
        val hash: kotlin.String? = null,
        @Json(name = "subType")
        val subType: Transaction.SubType? = null,
        @Json(name = "offchainId")
        val offchainId: kotlin.String? = null,
        @Json(name = "confirmations")
        val confirmations: java.math.BigDecimal? = null,
        @Json(name = "createdAt")
        val createdAt: java.time.OffsetDateTime? = null,
        @Json(name = "updatedAt")
        val updatedAt: java.time.OffsetDateTime? = null,
        @Json(name = "errorCode")
        val errorCode: Transaction.ErrorCode? = null
) {

    /**
     *
     * Values: created,pending,failed,success
     */

    enum class Status(val value: kotlin.String) {
        @Json(name = "created")
        created("created"),
        @Json(name = "pending")
        pending("pending"),
        @Json(name = "failed")
        failed("failed"),
        @Json(name = "success")
        success("success");
    }

    /**
     *
     * Values: payout,payin,deposit,withdraw,bankToExchange,exchangeToBank
     */

    enum class Type(val value: kotlin.String) {
        @Json(name = "payout")
        payout("payout"),
        @Json(name = "payin")
        payin("payin"),
        @Json(name = "deposit")
        deposit("deposit"),
        @Json(name = "withdraw")
        withdraw("withdraw"),
        @Json(name = "bankToExchange")
        bankToExchange("bankToExchange"),
        @Json(name = "exchangeToBank")
        exchangeToBank("exchangeToBank");
    }

    /**
     *
     * Values: offchain,swap
     */

    enum class SubType(val value: kotlin.String) {
        @Json(name = "offchain")
        offchain("offchain"),
        @Json(name = "swap")
        swap("swap");
    }

    /**
     *
     * Values: iNVALIDADDRESS,iNVALIDPAYMENTID,bADPRECISION
     */

    enum class ErrorCode(val value: kotlin.String) {
        @Json(name = "INVALID_ADDRESS")
        iNVALIDADDRESS("INVALID_ADDRESS"),
        @Json(name = "INVALID_PAYMENT_ID")
        iNVALIDPAYMENTID("INVALID_PAYMENT_ID"),
        @Json(name = "BAD_PRECISION")
        bADPRECISION("BAD_PRECISION");
    }
}

