package com.mycelium.wallet.pdf;


import java.text.DateFormat;
import java.util.Date;
import java.util.Locale;

import crl.android.pdfwriter.PaperSize;

public class InvoiceBuilder {
    public static final int MAX_SYMBOLS_ON_PAGE = 60;
    private String fromName;
    private String description;
    private String receiveAddress;
    private String amount;
    private String paymentUri;

    private PdfWriter writer;

    public InvoiceBuilder setFrom(String name) {
        this.fromName = name;
        return this;
    }

    public InvoiceBuilder setDescription(String description) {
        this.description = description;
        return this;
    }

    public InvoiceBuilder setReceiveAddress(String receiveAddress) {
        this.receiveAddress = receiveAddress;
        return this;
    }

    public InvoiceBuilder setAmount(String amount) {
        this.amount = amount;
        return this;
    }

    public InvoiceBuilder setPaymentUri(String paymentUri) {
        this.paymentUri = paymentUri;
        return this;
    }

    public String build(){
        int pageWidth = PaperSize.EXECUTIVE_WIDTH;
        int pageHeight = PaperSize.EXECUTIVE_HEIGHT;
        Date now = new Date();
        writer = new PdfWriter(pageWidth, pageHeight, 20, 20, 20, 20);
        double fromTop = 1.5F;
        writer.addText(1F, fromTop, 16, "From: " + fromName);

        Locale usLocale = new Locale("en_US");
        fromTop += 0.7F;
        writer.addText(1F, fromTop, 14, "Date: " + DateFormat.getDateInstance(DateFormat.LONG, usLocale).format(now));

        fromTop += 1.5F;
        writer.addText(7F, fromTop, 18, "INVOICE " + now.getTime() / 1000);

        fromTop += 1.5F;
        writer.addText(1F, fromTop, 18, "Description");

        fromTop += 0.8F;

        int carret = 0;
        while (carret + MAX_SYMBOLS_ON_PAGE < description.length()) {
            writer.addText(1F, fromTop, 16, description.substring(carret, carret + MAX_SYMBOLS_ON_PAGE));
            carret += MAX_SYMBOLS_ON_PAGE;
            fromTop += 0.7F;
        }
        writer.addText(1F, fromTop, 16, description.substring(carret));

        fromTop += 1F;
        writer.addText(1F, fromTop, 18, "Total: " + amount);

        fromTop += 2F;
        writer.addText(1F, fromTop, 18, "Payment address:");

        fromTop += 0.8F;
        writer.addText(1F, fromTop, 14, receiveAddress);

        fromTop += 0.6F;
        writer.addQrCode(2F, fromTop, 8, paymentUri);

        writer.addText(15F, 26.4F, 12, "Generated by Mycelium");
        return writer.asString();
    }
}
