/**
* Auth API
* Auth API<br> <a href='/changelog'>Changelog</a>
*
* The version of the OpenAPI document: v0.0.50
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.mycelium.bequant.remote.client.apis

import com.mycelium.bequant.remote.client.models.ApiKey
import com.mycelium.bequant.remote.client.models.ApiKeyDeleteRequest
import com.mycelium.bequant.remote.client.models.ApiKeyRequest
import com.mycelium.bequant.remote.client.models.Error
import com.mycelium.bequant.remote.client.models.SessionIssuesResponse

import com.mycelium.bequant.remote.client.RetrofitHolder
import retrofit2.Response
import retrofit2.Retrofit
import retrofit2.create
import retrofit2.http.*
import okhttp3.*
import retrofit2.http.Headers

interface ApiKeyApi {
    
    /**
    * Get API key
    * Get API key &lt;br&gt;&lt;b style&#x3D;\&quot;color:red;\&quot;&gt;Bearer access token required!&lt;/b&gt;
    * Responses:
    *  - 200: OK
    *  - 401: Api key is missing or invalid
    *  - 403: Api key is missing or invalid
    *  - 420: Session issues
    *  - 421: Token expired
    *  - 0: error
    * 
    * @param apiKeyRequest  (optional)
    * @return ApiKey
    */
    @POST("api-key")
    
    suspend fun postApiKey(
        @Body apiKeyRequest: ApiKeyRequest? = null
    ): Response<ApiKey>

    /**
    * Delete API key
    * Delete API key &lt;br&gt;&lt;b style&#x3D;\&quot;color:red;\&quot;&gt;Bearer access token required!&lt;/b&gt;
    * Responses:
    *  - 200: OK
    *  - 401: Api key is missing or invalid
    *  - 403: Api key is missing or invalid
    *  - 420: Session issues
    *  - 421: Token expired
    *  - 0: error
    * 
    * @param apiKeyDeleteRequest  (optional)
    * @return void
    */
    @POST("api-key/delete")
    
    suspend fun postApiKeyDelete(
        @Body apiKeyDeleteRequest: ApiKeyDeleteRequest? = null
    ): Response<Unit>


    companion object {
        fun create(retrofit: Retrofit = RetrofitHolder.retrofit): ApiKeyApi = retrofit.create()
    }
}
