/**
 * Auth API
 * Auth API<br> <a href='/changelog'>Changelog</a>
 *
 * The version of the OpenAPI document: v0.0.50
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.mycelium.bequant.remote.client.apis


import com.mycelium.bequant.remote.client.createApi
import retrofit2.Response
import retrofit2.http.GET

interface SwaggerApi {

    /**
     * swagger doc
     * swagger doc
     * Responses:
     *  - 200: OK
     *
     * @return kotlin.String
     */
    @GET("")

    suspend fun get(

    ): Response<kotlin.String>

    /**
     * Changelog
     * Changelog
     * Responses:
     *  - 200: OK
     *
     * @return kotlin.String
     */
    @GET("changelog")

    suspend fun getChangelog(

    ): Response<kotlin.String>

    /**
     * swagger.json
     * swagger.json
     * Responses:
     *  - 200: OK
     *
     * @return kotlin.String
     */
    @GET("swagger.json")

    suspend fun getSwaggerJson(

    ): Response<kotlin.String>


    companion object {
        fun create(): SwaggerApi = createApi()
    }
}
