plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.android)
}

android {
    compileSdk = libs.versions.android.compileSdk.get().toInteger()

    defaultConfig {
        minSdk = libs.versions.android.minSdk.get().toInteger()
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
    namespace 'com.mycelium.view'

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }

    kotlinOptions {
        jvmTarget = "21"
    }
    lint {
        targetSdk 36
    }
    testOptions {
        targetSdk 36
    }
}

dependencies {
    implementation libs.recyclerview
    implementation "androidx.appcompat:appcompat:$appCompatVersion"
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}

