///**
// * Gift Cards Shop API
// * Products catalog, checkout and orders API - allows realtime purchase of products
// *
// * The version of the OpenAPI document: 1.0
// *
// *
// * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
// * https://openapi-generator.tech
// * Do not edit the class manually.
// */
//package com.mycelium.giftbox.client.models
//
//
//import android.os.Parcelable
//import com.fasterxml.jackson.annotation.JsonProperty
//import kotlinx.android.parcel.Parcelize
//
///**
// * Minimal amount of information needed to display a list of products
// * @param cardImageUrl Url of card image
// * @param code Unique product code/id
// * @param name Product name
// */
//@Parcelize
//
//data class BasicProductInfo(
//    /* Url of card image */
//    @JsonProperty("card_image_url")
//    var cardImageUrl: String? = null,
//    /* Unique product code/id */
//    @JsonProperty("code")
//    var code: String? = null,
//    /* Product name */
//    @JsonProperty("name")
//    var name: String? = null
//) : Parcelable
//
