/**
 * Gift Cards Shop API
 * Products catalog, checkout and orders API - allows realtime purchase of products
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.mycelium.giftbox.client.models


import android.os.Parcelable
import com.fasterxml.jackson.annotation.JsonProperty
import kotlinx.android.parcel.Parcelize

/**
 * Parameters to create new order
 * @param amount Value of product in product currency
 * @param clientOrderId Unique client order id
 * @param clientUserId Unique client user id
 * @param currencyId Get price offer in this currency
 * @param quantity Number of products in purchase
 * @param code Product code
 */
@Parcelize

data class CreateOrderRequest(
    /* Value of product in product currency */
    @JsonProperty("amount")
    var amount: String,
    /* Unique client order id */
    @JsonProperty("client_order_id")
    var clientOrderId: String,
    /* Unique client user id */
    @JsonProperty("client_user_id")
    var clientUserId: String,
    /* Get price offer in this currency */
    @JsonProperty("currency_id")
    var currencyId: String,
    /* Number of products in purchase */
    @JsonProperty("quantity")
    var quantity: String,
    /* Product code */
    @JsonProperty("code")
    var code: String
) : Parcelable

