/**
 * Gift Cards Shop API
 * Products catalog, checkout and orders API - allows realtime purchase of products
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.mycelium.giftbox.client.models


import android.os.Parcelable
import com.fasterxml.jackson.annotation.JsonProperty
import kotlinx.android.parcel.Parcelize

/**
 * Payment currency info
 * @param extraIdName Extra ID - used together with the send address for some blockchains (e.g EOS, XLM, etc..)
 * @param fullName Full name of currency
 * @param name Currency short code
 * @param contractAddress Address of smart contract (where relevant)
 */
@Parcelize

data class CurrencyInfo(
    /* Extra ID - used together with the send address for some blockchains (e.g EOS, XLM, etc..) */
    @JsonProperty("extraIdName")
    var extraIdName: String? = null,
    /* Full name of currency */
    @JsonProperty("fullName")
    var fullName: String? = null,
    /* Currency short code */
    @JsonProperty("name")
    var name: String? = null,
    /* Address of smart contract (where relevant) */
    @JsonProperty("contractAddress")
    var contractAddress: String? = null
) : Parcelable

class CurrencyInfos : ArrayList<CurrencyInfo>()