/**
 * Gift Cards Shop API
 * Products catalog, checkout and orders API - allows realtime purchase of products
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.mycelium.giftbox.client.models

import android.os.Parcelable
import com.fasterxml.jackson.annotation.JsonProperty
import kotlinx.android.parcel.Parcelize
import java.util.*

/**
 * Status and product information needed for display, as well as the products (codes for giftcards)
 * @param amount Value of product in product currency
 * @param clientOrderId Unique client order id
 * @param items List of giftcard codes
 * @param productCode Product code
 * @param productImg Url of card image
 * @param productName Product name
 * @param quantity Number of products in purchase
 * @param status Order status
 * @param timestamp Date time of order creation
 */
@Parcelize

data class Order(
    /* Value of product in product currency */
    @JsonProperty("amount")
    var amount: String? = null,
    /* Unique client order id */
    @JsonProperty("client_order_id")
    var clientOrderId: String? = null,
    /* List of giftcard codes */
    @JsonProperty("items")
    var items: List<Ecode>? = null,
    /* Product code */
    @JsonProperty("product_code")
    var productCode: String? = null,
    /* Url of card image */
    @JsonProperty("product_img")
    var productImg: String? = null,
    /* Product name */
    @JsonProperty("product_name")
    var productName: String? = null,
    /* Number of products in purchase */
    @JsonProperty("quantity")
    var quantity: String? = null,
    /* Order status */
    @JsonProperty("status")
    var status: Status? = null,
    /* Date time of order creation */
    @JsonProperty("timestamp")
    var timestamp: Date? = null
) : Parcelable {

    /**
     * Order status
     * Values: sUCCESS,eRROR,pROCESSING
     */

    enum class Status(val value: String) {
        @JsonProperty(value = "SUCCESS")
        sUCCESS("SUCCESS"),
        @JsonProperty(value = "ERROR")
        eRROR("ERROR"),
        @JsonProperty(value = "PROCESSING")
        pROCESSING("PROCESSING");
    }
}

