/**
 * Gift Cards Shop API
 * Products catalog, checkout and orders API - allows realtime purchase of products
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.mycelium.giftbox.client.models

import android.os.Parcelable
import com.fasterxml.jackson.annotation.JsonProperty
import kotlinx.android.parcel.Parcelize

/**
 * userâ€™s orders, including status and product information needed for display, as well as the products (codes for giftcards)
 * @param items List of orders
 * @param size Total amount of orders available. Can be used for paging.
 * @param status Order status
 */
@Parcelize

data class OrdersHistoryResponse(
    /* List of orders */
    @JsonProperty("items")
    var items: List<Order>? = null,
    /* Total amount of orders available. Can be used for paging. */
    @JsonProperty("size")
    var size: Long? = null,
    /* Order status */
    @JsonProperty("status")
    var status: Status? = null
) : Parcelable {

    /**
     * Order status
     * Values: sUCCESS,eRROR
     */

    enum class Status(val value: kotlin.String) {
        @JsonProperty(value = "SUCCESS")
        sUCCESS("SUCCESS"),
        @JsonProperty(value = "ERROR")
        eRROR("ERROR");
    }
}

