/**
 * Gift Cards Shop API
 * Products catalog, checkout and orders API - allows realtime purchase of products
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.mycelium.giftbox.client.models

import android.os.Parcelable
import com.fasterxml.jackson.annotation.JsonProperty
import kotlinx.parcelize.Parcelize
import java.math.BigDecimal
import java.util.*

/**
 * Status and product information needed for display, as well as the products (codes for giftcards)
 * @param amount Value of product in product currency
 * @param clientOrderId Unique client order id
 * @param items List of giftcard codes
 * @param productCode Product code
 * @param productImg Url of card image
 * @param productName Product name
 * @param quantity Number of products in purchase
 * @param status Order status
 * @param timestamp Date time of order creation
 */
@Parcelize

open class Order(
    /* Value of product in product currency */
    @JsonProperty("amount")
    open var amount: String? = null,
    /* Product currency code */
    @JsonProperty("currency_code")
    open var currencyCode: String? = null,
    /* Unique client order id */
    @JsonProperty("client_order_id")
    open var clientOrderId: String? = null,
    /* List of giftcard codes */
    @JsonProperty("items")
    open var items: List<Ecode>? = null,
    /* Product code */
    @JsonProperty("product_code")
    open var productCode: String? = null,
    /* Url of card image */
    @JsonProperty("product_img")
    open var productImg: String? = null,
    /* Product name */
    @JsonProperty("product_name")
    open var productName: String? = null,
    /* Number of products in purchase */
    @JsonProperty("quantity")
    open var quantity: BigDecimal? = null,
    /* Order status */
    @JsonProperty("status")
    open var status: Status? = null,
    /* Date time of order creation */
    @JsonProperty("timestamp")
    open var timestamp: Date? = null
) : Parcelable
