/**
 * Gift Cards Shop API
 * Products catalog, checkout and orders API - allows realtime purchase of products
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.mycelium.giftbox.client.models


import android.os.Parcelable
import com.fasterxml.jackson.annotation.JsonProperty
import kotlinx.android.parcel.Parcelize

/**
 * Price offer for a given product quantity, amount and currency
 * @param priceOffer Price of selected amount and quantity in given currency_id
 * @param status Status - success or failure of request
 */
@Parcelize

data class PriceResponse(
    /* Price of selected amount and quantity in given currency_id */
    @JsonProperty("priceOffer")
    var priceOffer: kotlin.String? = null,
    /* Status - success or failure of request */
    @JsonProperty("status")
    var status: Status? = null,
    @JsonProperty("exchangeRate")
    var exchangeRate: kotlin.String? = null
) : Parcelable {

    /**
     * Status - success or failure of request
     * Values: sUCCESS,eRRORTOOHIGH,eRROR
     */

    enum class Status(val value: kotlin.String) {
        @JsonProperty(value = "SUCCESS")
        sUCCESS("SUCCESS"),
        @JsonProperty(value = "ERROR_TOO_HIGH")
        eRRORTOOHIGH("ERROR_TOO_HIGH"),
        @JsonProperty(value = "ERROR")
        eRROR("ERROR");
    }
}

