/**
 * Gift Cards Shop API
 * Products catalog, checkout and orders API - allows realtime purchase of products
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.mycelium.giftbox.client.models

import android.os.Parcelable
import com.fasterxml.jackson.annotation.JsonProperty
import kotlinx.android.parcel.Parcelize

/**
 * Product info, price offer, similar products
 * @param priceCurrency Currency of price offer. By default BTC.
 * @param priceOffer Price of selected amount and quantity in currency. By default BTC
 * @param product
 * @param similarProducts List of additional products to display
 */
@Parcelize

data class ProductResponse(
    /* Currency of price offer. By default BTC. */
    @JsonProperty("priceCurrency")
    var priceCurrency: kotlin.String? = null,
    /* Price of selected amount and quantity in currency. By default BTC */
    @JsonProperty("priceOffer")
    var priceOffer: kotlin.String? = null,
    @JsonProperty("product")
    var product: ProductInfo? = null,
    /* List of additional products to display */
    @JsonProperty("similarProducts")
    var similarProducts: List<ProductInfo>? = null
) : Parcelable

